name: Github Actions 연습하기

on:
  push:
    branshes:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 여러 명령어 문장 작성하기 
        run: |
          echo "Good"
          echo "Morning"

      - name: Github Actions에 이미 존재하는 변수를 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: Github Actions Secret 변수 사용해보기
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_HOBBY }}
